//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/strings.ps1 from Strings.resx. Do not edit by hand.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace Omnimud.Core.Resources;

/// <summary>
/// A strongly-typed resource class for looking up localized strings.
/// </summary>
internal static class Strings
{
    private static ResourceManager? _resourceManager;

    private static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("Omnimud.Core.Resources.Strings", typeof(Strings).Assembly);

    internal static CultureInfo? Culture { get; set; }

    internal static string Error_CannotConnectInState => ResourceManager.GetString("Error_CannotConnectInState", Culture) ?? "";
    internal static string Error_PortOutOfRange => ResourceManager.GetString("Error_PortOutOfRange", Culture) ?? "";
    internal static string Error_ConnectionTimedOut => ResourceManager.GetString("Error_ConnectionTimedOut", Culture) ?? "";
    internal static string Error_NotConnected => ResourceManager.GetString("Error_NotConnected", Culture) ?? "";
    internal static string Error_ScriptTimedOut => ResourceManager.GetString("Error_ScriptTimedOut", Culture) ?? "";
    internal static string Error_ScriptInstructionLimit => ResourceManager.GetString("Error_ScriptInstructionLimit", Culture) ?? "";
    internal static string Error_ScriptRuntime => ResourceManager.GetString("Error_ScriptRuntime", Culture) ?? "";
    internal static string Error_ScriptSyntax => ResourceManager.GetString("Error_ScriptSyntax", Culture) ?? "";
    internal static string Error_OnlyHttpsAllowed => ResourceManager.GetString("Error_OnlyHttpsAllowed", Culture) ?? "";
    internal static string Error_ExtensionNotAllowed => ResourceManager.GetString("Error_ExtensionNotAllowed", Culture) ?? "";
    internal static string Error_FileTooLarge => ResourceManager.GetString("Error_FileTooLarge", Culture) ?? "";
    internal static string Error_MasterKeySize => ResourceManager.GetString("Error_MasterKeySize", Culture) ?? "";
    internal static string Error_ProtectedDataTooShort => ResourceManager.GetString("Error_ProtectedDataTooShort", Culture) ?? "";
    internal static string Cmd_Offline => ResourceManager.GetString("Cmd_Offline", Culture) ?? "";
    internal static string Cmd_NotConnected => ResourceManager.GetString("Cmd_NotConnected", Culture) ?? "";
    internal static string Cmd_RecursionLimit => ResourceManager.GetString("Cmd_RecursionLimit", Culture) ?? "";
    internal static string Cmd_RequiresCharacter => ResourceManager.GetString("Cmd_RequiresCharacter", Culture) ?? "";
    internal static string Cmd_ClsOk => ResourceManager.GetString("Cmd_ClsOk", Culture) ?? "";
    internal static string Path_NoDirections => ResourceManager.GetString("Path_NoDirections", Culture) ?? "";
    internal static string Path_Usage => ResourceManager.GetString("Path_Usage", Culture) ?? "";
    internal static string Path_NotFound => ResourceManager.GetString("Path_NotFound", Culture) ?? "";
    internal static string Path_NotReversible => ResourceManager.GetString("Path_NotReversible", Culture) ?? "";
    internal static string Path_Invalid => ResourceManager.GetString("Path_Invalid", Culture) ?? "";
    internal static string Triggers_Disabled => ResourceManager.GetString("Triggers_Disabled", Culture) ?? "";
    internal static string Triggers_Enabled => ResourceManager.GetString("Triggers_Enabled", Culture) ?? "";
    internal static string Triggers_AlreadyDisabled => ResourceManager.GetString("Triggers_AlreadyDisabled", Culture) ?? "";
    internal static string Triggers_AlreadyEnabled => ResourceManager.GetString("Triggers_AlreadyEnabled", Culture) ?? "";
    internal static string Trigger_EnableWhich => ResourceManager.GetString("Trigger_EnableWhich", Culture) ?? "";
    internal static string Trigger_DisableWhich => ResourceManager.GetString("Trigger_DisableWhich", Culture) ?? "";
    internal static string Trigger_NotFound => ResourceManager.GetString("Trigger_NotFound", Culture) ?? "";
    internal static string Trigger_AlreadyEnabled => ResourceManager.GetString("Trigger_AlreadyEnabled", Culture) ?? "";
    internal static string Trigger_AlreadyDisabled => ResourceManager.GetString("Trigger_AlreadyDisabled", Culture) ?? "";
    internal static string Trigger_EnabledOk => ResourceManager.GetString("Trigger_EnabledOk", Culture) ?? "";
    internal static string Trigger_DisabledOk => ResourceManager.GetString("Trigger_DisabledOk", Culture) ?? "";
    internal static string Trigger_EnableError => ResourceManager.GetString("Trigger_EnableError", Culture) ?? "";
    internal static string Trigger_DisableError => ResourceManager.GetString("Trigger_DisableError", Culture) ?? "";
    internal static string Alias_RemoveNeedsName => ResourceManager.GetString("Alias_RemoveNeedsName", Culture) ?? "";
    internal static string Alias_NameNoSpaces => ResourceManager.GetString("Alias_NameNoSpaces", Culture) ?? "";
    internal static string Alias_NotFound => ResourceManager.GetString("Alias_NotFound", Culture) ?? "";
    internal static string Alias_Removed => ResourceManager.GetString("Alias_Removed", Culture) ?? "";
    internal static string Alias_RemoveError => ResourceManager.GetString("Alias_RemoveError", Culture) ?? "";
    internal static string Alias_QueryNeedsName => ResourceManager.GetString("Alias_QueryNeedsName", Culture) ?? "";
    internal static string Alias_Assigned => ResourceManager.GetString("Alias_Assigned", Culture) ?? "";
    internal static string Alias_NotStored => ResourceManager.GetString("Alias_NotStored", Culture) ?? "";
    internal static string Alias_EmptyCommand => ResourceManager.GetString("Alias_EmptyCommand", Culture) ?? "";
    internal static string Alias_EmptyAction => ResourceManager.GetString("Alias_EmptyAction", Culture) ?? "";
    internal static string Alias_AlreadyExists => ResourceManager.GetString("Alias_AlreadyExists", Culture) ?? "";
    internal static string Alias_SameActionConfirm => ResourceManager.GetString("Alias_SameActionConfirm", Culture) ?? "";
    internal static string Alias_Cancelled => ResourceManager.GetString("Alias_Cancelled", Culture) ?? "";
    internal static string Alias_Added => ResourceManager.GetString("Alias_Added", Culture) ?? "";
    internal static string Alias_AddError => ResourceManager.GetString("Alias_AddError", Culture) ?? "";
    internal static string Rec_AlreadyStarted => ResourceManager.GetString("Rec_AlreadyStarted", Culture) ?? "";
    internal static string Rec_Started => ResourceManager.GetString("Rec_Started", Culture) ?? "";
    internal static string Rec_NotRecording => ResourceManager.GetString("Rec_NotRecording", Culture) ?? "";
    internal static string Rec_Empty => ResourceManager.GetString("Rec_Empty", Culture) ?? "";
    internal static string Rec_Last => ResourceManager.GetString("Rec_Last", Culture) ?? "";
    internal static string Rec_LastRemoved => ResourceManager.GetString("Rec_LastRemoved", Culture) ?? "";
    internal static string Rec_Recorded => ResourceManager.GetString("Rec_Recorded", Culture) ?? "";
    internal static string Rec_CancelConfirm => ResourceManager.GetString("Rec_CancelConfirm", Culture) ?? "";
    internal static string Rec_Cancelled => ResourceManager.GetString("Rec_Cancelled", Culture) ?? "";
    internal static string Rec_Stopped => ResourceManager.GetString("Rec_Stopped", Culture) ?? "";
    internal static string Rec_Status => ResourceManager.GetString("Rec_Status", Culture) ?? "";
    internal static string Silent_On => ResourceManager.GetString("Silent_On", Culture) ?? "";
    internal static string Silent_AlreadyOn => ResourceManager.GetString("Silent_AlreadyOn", Culture) ?? "";
    internal static string Silent_Off => ResourceManager.GetString("Silent_Off", Culture) ?? "";
    internal static string Silent_NotOn => ResourceManager.GetString("Silent_NotOn", Culture) ?? "";
    internal static string Session_ServerClosed => ResourceManager.GetString("Session_ServerClosed", Culture) ?? "";
    internal static string Session_ConnectionLost => ResourceManager.GetString("Session_ConnectionLost", Culture) ?? "";
    internal static string Session_ConnectionTimeout => ResourceManager.GetString("Session_ConnectionTimeout", Culture) ?? "";
    internal static string Session_SendError => ResourceManager.GetString("Session_SendError", Culture) ?? "";
    internal static string Session_ScriptError => ResourceManager.GetString("Session_ScriptError", Culture) ?? "";
    internal static string Session_InvalidGetPattern => ResourceManager.GetString("Session_InvalidGetPattern", Culture) ?? "";
    internal static string Log_SessionEnded => ResourceManager.GetString("Log_SessionEnded", Culture) ?? "";
    internal static string Log_OpenError => ResourceManager.GetString("Log_OpenError", Culture) ?? "";
    internal static string Session_MessageScriptError => ResourceManager.GetString("Session_MessageScriptError", Culture) ?? "";
    internal static string Session_MessageScriptDisabled => ResourceManager.GetString("Session_MessageScriptDisabled", Culture) ?? "";
    internal static string Actions_Inventory => ResourceManager.GetString("Actions_Inventory", Culture) ?? "";
    internal static string Actions_Exits => ResourceManager.GetString("Actions_Exits", Culture) ?? "";
    internal static string Actions_More => ResourceManager.GetString("Actions_More", Culture) ?? "";
    internal static string Proxy_ConnectionFailed => ResourceManager.GetString("Proxy_ConnectionFailed", Culture) ?? "";
    internal static string Proxy_AuthenticationFailed => ResourceManager.GetString("Proxy_AuthenticationFailed", Culture) ?? "";
    internal static string Proxy_Rejected => ResourceManager.GetString("Proxy_Rejected", Culture) ?? "";
    internal static string Proxy_RejectedWithCode => ResourceManager.GetString("Proxy_RejectedWithCode", Culture) ?? "";
    internal static string Proxy_ProtocolError => ResourceManager.GetString("Proxy_ProtocolError", Culture) ?? "";
    internal static string Proxy_NameSocks5 => ResourceManager.GetString("Proxy_NameSocks5", Culture) ?? "";
    internal static string Proxy_NameHttpConnect => ResourceManager.GetString("Proxy_NameHttpConnect", Culture) ?? "";
}
