using System.Text.RegularExpressions;
using System.Xml.Linq;
using FluentAssertions;

namespace Omnimud.Core.Tests.Localization;

/// <summary>
/// The localized strings of Core and UI, checked from the source files: both languages carry
/// exactly the same keys, no value is empty, and Strings.Designer.cs (generated by
/// tools/strings.ps1) matches Strings.resx.
/// </summary>
public sealed partial class StringResourcesTests
{
    [Theory]
    [InlineData("Core")]
    [InlineData("UI")]
    public void NeutralAndSpanish_HaveExactlyTheSameKeys(string project)
    {
        var neutral = Load(project, "Strings.resx");
        var spanish = Load(project, "Strings.es.resx");

        neutral.Should().NotBeEmpty();
        neutral.Select(e => e.Key).Should().OnlyHaveUniqueItems();
        spanish.Select(e => e.Key).Should().OnlyHaveUniqueItems();
        spanish.Select(e => e.Key).Except(neutral.Select(e => e.Key)).Should().BeEmpty("every Spanish key exists in the neutral file");
        neutral.Select(e => e.Key).Except(spanish.Select(e => e.Key)).Should().BeEmpty("every neutral key is translated");
    }

    [Theory]
    [InlineData("Core", "Strings.resx")]
    [InlineData("Core", "Strings.es.resx")]
    [InlineData("UI", "Strings.resx")]
    [InlineData("UI", "Strings.es.resx")]
    public void NoValueIsEmpty(string project, string file)
    {
        Load(project, file).Where(e => string.IsNullOrWhiteSpace(e.Value)).Select(e => e.Key).Should().BeEmpty();
    }

    [Theory]
    [InlineData("Core")]
    [InlineData("UI")]
    public void BothLanguages_UseTheSameFormatPlaceholders(string project)
    {
        var spanish = Load(project, "Strings.es.resx").ToDictionary(e => e.Key, e => e.Value);

        var different = Load(project, "Strings.resx")
            .Where(e => spanish.TryGetValue(e.Key, out var es) && !Placeholders(e.Value).SetEquals(Placeholders(es)))
            .Select(e => e.Key);

        different.Should().BeEmpty();
    }

    [Theory]
    [InlineData("Core")]
    [InlineData("UI")]
    public void Designer_IsInSyncWithTheNeutralFile(string project)
    {
        var designer = File.ReadAllText(Path.Combine(ResourceDirectory(project), "Strings.Designer.cs"));
        var properties = DesignerProperty().Matches(designer).Select(m => (Property: m.Groups[1].Value, Key: m.Groups[2].Value)).ToList();

        properties.Should().OnlyContain(p => p.Property == p.Key);
        properties.Select(p => p.Key).Should().Equal(Load(project, "Strings.resx").Select(e => e.Key),
            "run Update-OmStringsDesigner {0} (tools/strings.ps1) after editing the .resx", project);
    }

    private static HashSet<string> Placeholders(string value) =>
        Placeholder().Matches(value.Replace("{{", string.Empty).Replace("}}", string.Empty)).Select(m => m.Groups[1].Value).ToHashSet();

    private static List<(string Key, string Value)> Load(string project, string file) =>
        XDocument.Load(Path.Combine(ResourceDirectory(project), file)).Root!
            .Elements("data")
            .Select(d => ((string)d.Attribute("name")!, (string?)d.Element("value") ?? string.Empty))
            .ToList();

    private static string ResourceDirectory(string project)
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Omnimud.sln")))
            directory = directory.Parent;

        directory.Should().NotBeNull("the tests run from inside the repository");
        return Path.Combine(directory!.FullName, "src", $"Omnimud.{project}", "Resources");
    }

    [GeneratedRegex(@"static string (\w+) => ResourceManager\.GetString\(""(\w+)""")]
    private static partial Regex DesignerProperty();

    [GeneratedRegex(@"\{(\d+)[^}]*\}")]
    private static partial Regex Placeholder();
}
